#Wed May 27 17:38:20 EDT 2026
archives_base_name=entstupidstuff
fabric_version=0.135.0+1.21.10
loader_version=0.17.3
loom_version=1.11-SNAPSHOT
maven_group=net.ent.entstupidstuff
minecraft_version=1.21.10
mod_version=0.0.15
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
